manifest:
    remotes:
        - name: urob
          url-base: https://github.com/urob
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
    self:
        path: config
